defaults:
- data: zarr
- dataloader: native_grid
- diagnostics: eval_rollout
- hardware: example
- graph: stretched_multi_scale
- model: gnn
- training: default
- _self_


### This file is for local experimentation.
##  When you commit your changes, assign the new features and keywords
##  to the correct defaults.
# For example to change from default GPU count:
# hardware:
#   num_gpus_per_node: 1

data:
  resolution: ??? # must match the resolution of the regional dataset
  forcing: ???
  diagnostic: []
  normalizer:
    max: []
    none: ???
diagnostics:
  plot:
    enabled: True
    parameters: ???
    parameters_histogram: ???
    parameters_spectrum: [] #Â WIP: spectrum plots not supported for LAM
    learned_features: False
hardware:
  files:
    graph: ???
model:
  num_channels: 128
dataloader:
  dataset:
    cutout:
      - dataset: ${hardware.paths.data}/${hardware.files.dataset}
        thinning: ${graph.nodes.data.node_builder.thinning}
      - dataset: ${hardware.paths.data}/${hardware.files.forcing_dataset}
    adjust: all
  limit_batches:
    training: 100
    validation: 100
training:
  max_epochs: 5
